"""twat-hook.ts generator (Qt-free).

Generates `.pi/extensions/twat-hook.ts` into a project. The hook reads
TWAT_HOOK_PORT / TWAT_HOOK_TOKEN / TWAT_SESSION_ID from the process env at
runtime and POSTs lifecycle events to TWAT's localhost listener. Failures are
swallowed so direct `pi` use is never broken. See ADR-0002 and
docs/specs/session/lifecycle-hook.md.
"""

from __future__ import annotations

from pathlib import Path

HOOK_FILENAME = "twat-hook.ts"

_HOOK_TEMPLATE = """\
// @twat-version {version}
// TWAT lifecycle hook. Auto-generated by TWAT; do not edit by hand.
// Reads connection details from the process env at runtime (not baked in).
// All errors are swallowed so direct `pi` use is never broken.
// You may add `.pi/extensions/twat-hook.ts` to your .gitignore if you wish.

import type {{ ExtensionAPI }} from "@earendil-works/pi-coding-agent";

const PORT = process.env.TWAT_HOOK_PORT;
const TOKEN = process.env.TWAT_SESSION_ID ? process.env.TWAT_HOOK_TOKEN : undefined;
const SESSION_ID = process.env.TWAT_SESSION_ID;

async function emit(payload: Record<string, unknown>): Promise<void> {{
  if (!PORT || !TOKEN || !SESSION_ID) return;
  try {{
    await fetch(`http://127.0.0.1:${{PORT}}/hook`, {{
      method: "POST",
      headers: {{ "Content-Type": "application/json", "X-Twat-Token": TOKEN }},
      body: JSON.stringify({{ sessionId: SESSION_ID, ...payload }}),
    }});
  }} catch {{
    // best-effort: never break pi
  }}
}}

export default function (pi: ExtensionAPI) {{
  pi.on("session_start", async (_event, ctx) => {{
    const sessionFile = ctx.sessionManager.getSessionFile() ?? null;
    const name = pi.getSessionName() ?? null;
    await emit({{ type: "session_start", sessionFile, name }});
  }});

  pi.on("agent_start", async () => {{
    await emit({{ type: "agent_activity", activity: "working" }});
  }});

  pi.on("agent_end", async () => {{
    await emit({{ type: "agent_activity", activity: "idle" }});
  }});

  pi.on("turn_end", async () => {{
    const name = pi.getSessionName() ?? null;
    await emit({{ type: "name", name }});
  }});

  pi.on("session_shutdown", async () => {{
    await emit({{ type: "session_shutdown" }});
  }});

  // Rename: canonical instant path via /twat-rename.
  pi.registerCommand("twat-rename", {{
    description: "Rename this session in TWAT (usage: /twat-rename <name>)",
    handler: async (args, _ctx) => {{
      const name = args.trim();
      if (!name) return;
      pi.setSessionName(name);
      await emit({{ type: "name", name }});
    }},
  }});

  // /twat status: report TWAT connection + session state in the pi terminal.
  // Read-only; never mutates state. Best-effort: failures just notify.
  pi.registerCommand("twat-status", {{
    description: "Show this session's TWAT connection status",
    handler: async (_args, ctx) => {{
      if (!PORT || !TOKEN || !SESSION_ID) {{
        ctx.ui.notify("TWAT: not running under TWAT (no hook env).", "warn");
        return;
      }}
      try {{
        const r = await fetch(`http://127.0.0.1:${{PORT}}/status?sessionId=${{SESSION_ID}}`, {{
          headers: {{ "X-Twat-Token": TOKEN }},
        }});
        if (!r.ok) {{
          ctx.ui.notify(`TWAT: status request failed (HTTP ${{r.status}}).`, "warn");
          return;
        }}
        const s = (await r.json()) as Record<string, unknown>;
        const lines = [
          `TWAT session: ${{s.name ?? SESSION_ID}}`,
          `  state: ${{s.state}}`,
          `  agent: ${{s.agent_activity}}`,
          `  archived: ${{s.archived}}`,
          `  bound file: ${{s.bound_file ?? "(unbound)"}}`,
          `  hook: connected (port ${{PORT}})`,
        ];
        ctx.ui.notify(lines.join("\n"), "info");
      }} catch {{
        ctx.ui.notify("TWAT: could not reach the TWAT listener.", "warn");
      }}
    }},
  }});
}}
"""


def render_hook(*, version: str) -> str:
    return _HOOK_TEMPLATE.format(version=version)


def hook_path(project_path: str | Path) -> Path:
    return Path(project_path) / ".pi" / "extensions" / HOOK_FILENAME


def _read_version(path: Path) -> str | None:
    if not path.exists():
        return None
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("// @twat-version"):
            parts = line.split()
            return parts[2] if len(parts) >= 3 else None
    return None


def needs_update(project_path: str | Path, version: str) -> bool:
    return _read_version(hook_path(project_path)) != version


def write_hook(project_path: str | Path, version: str) -> None:
    path = hook_path(project_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_hook(version=version), encoding="utf-8")
